/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum CameraMode
{
  VIDEO = 0,
  PICTURE = 1,
  THERMAL = 2,
  ERROR = 3,
}
