/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;



public partial class DroneSendVideoRequest : TBase
{
  private string _rtp_url;
  private VideoType _video_type;

  public string RtpUrl
  {
    get
    {
      return _rtp_url;
    }
    set
    {
      __isset.rtp_url = true;
      this._rtp_url = value;
    }
  }

  /// <summary>
  /// 
  /// <seealso cref="VideoType"/>
  /// </summary>
  public VideoType VideoType
  {
    get
    {
      return _video_type;
    }
    set
    {
      __isset.video_type = true;
      this._video_type = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool rtp_url;
    public bool video_type;
  }

  public DroneSendVideoRequest()
  {
  }

  public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String)
            {
              RtpUrl = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.I32)
            {
              VideoType = (VideoType)await iprot.ReadI32Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("DroneSendVideoRequest");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      if (RtpUrl != null && __isset.rtp_url)
      {
        field.Name = "rtp_url";
        field.Type = TType.String;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteStringAsync(RtpUrl, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (__isset.video_type)
      {
        field.Name = "video_type";
        field.Type = TType.I32;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI32Async((int)VideoType, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    var other = that as DroneSendVideoRequest;
    if (other == null) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.rtp_url == other.__isset.rtp_url) && ((!__isset.rtp_url) || (System.Object.Equals(RtpUrl, other.RtpUrl))))
      && ((__isset.video_type == other.__isset.video_type) && ((!__isset.video_type) || (System.Object.Equals(VideoType, other.VideoType))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if(__isset.rtp_url)
        hashcode = (hashcode * 397) + RtpUrl.GetHashCode();
      if(__isset.video_type)
        hashcode = (hashcode * 397) + VideoType.GetHashCode();
    }
    return hashcode;
  }

  public override string ToString()
  {
    var sb = new StringBuilder("DroneSendVideoRequest(");
    bool __first = true;
    if (RtpUrl != null && __isset.rtp_url)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("RtpUrl: ");
      sb.Append(RtpUrl);
    }
    if (__isset.video_type)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("VideoType: ");
      sb.Append(VideoType);
    }
    sb.Append(")");
    return sb.ToString();
  }
}

