/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;



public partial class DroneVideoStateResult : TBase
{
  private DroneVideoState _state;
  private string _human_message;
  private string _rtp_url;
  private string _serial;
  private long _timestamp;

  /// <summary>
  /// 
  /// <seealso cref="DroneVideoState"/>
  /// </summary>
  public DroneVideoState State
  {
    get
    {
      return _state;
    }
    set
    {
      __isset.state = true;
      this._state = value;
    }
  }

  public string HumanMessage
  {
    get
    {
      return _human_message;
    }
    set
    {
      __isset.human_message = true;
      this._human_message = value;
    }
  }

  public string RtpUrl
  {
    get
    {
      return _rtp_url;
    }
    set
    {
      __isset.rtp_url = true;
      this._rtp_url = value;
    }
  }

  public string Serial
  {
    get
    {
      return _serial;
    }
    set
    {
      __isset.serial = true;
      this._serial = value;
    }
  }

  public long Timestamp
  {
    get
    {
      return _timestamp;
    }
    set
    {
      __isset.timestamp = true;
      this._timestamp = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool state;
    public bool human_message;
    public bool rtp_url;
    public bool serial;
    public bool timestamp;
  }

  public DroneVideoStateResult()
  {
  }

  public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32)
            {
              State = (DroneVideoState)await iprot.ReadI32Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.String)
            {
              HumanMessage = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.String)
            {
              RtpUrl = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.String)
            {
              Serial = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.I64)
            {
              Timestamp = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("DroneVideoStateResult");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      if (__isset.state)
      {
        field.Name = "state";
        field.Type = TType.I32;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI32Async((int)State, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (HumanMessage != null && __isset.human_message)
      {
        field.Name = "human_message";
        field.Type = TType.String;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteStringAsync(HumanMessage, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (RtpUrl != null && __isset.rtp_url)
      {
        field.Name = "rtp_url";
        field.Type = TType.String;
        field.ID = 3;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteStringAsync(RtpUrl, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (Serial != null && __isset.serial)
      {
        field.Name = "serial";
        field.Type = TType.String;
        field.ID = 4;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteStringAsync(Serial, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (__isset.timestamp)
      {
        field.Name = "timestamp";
        field.Type = TType.I64;
        field.ID = 5;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI64Async(Timestamp, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    var other = that as DroneVideoStateResult;
    if (other == null) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.state == other.__isset.state) && ((!__isset.state) || (System.Object.Equals(State, other.State))))
      && ((__isset.human_message == other.__isset.human_message) && ((!__isset.human_message) || (System.Object.Equals(HumanMessage, other.HumanMessage))))
      && ((__isset.rtp_url == other.__isset.rtp_url) && ((!__isset.rtp_url) || (System.Object.Equals(RtpUrl, other.RtpUrl))))
      && ((__isset.serial == other.__isset.serial) && ((!__isset.serial) || (System.Object.Equals(Serial, other.Serial))))
      && ((__isset.timestamp == other.__isset.timestamp) && ((!__isset.timestamp) || (System.Object.Equals(Timestamp, other.Timestamp))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if(__isset.state)
        hashcode = (hashcode * 397) + State.GetHashCode();
      if(__isset.human_message)
        hashcode = (hashcode * 397) + HumanMessage.GetHashCode();
      if(__isset.rtp_url)
        hashcode = (hashcode * 397) + RtpUrl.GetHashCode();
      if(__isset.serial)
        hashcode = (hashcode * 397) + Serial.GetHashCode();
      if(__isset.timestamp)
        hashcode = (hashcode * 397) + Timestamp.GetHashCode();
    }
    return hashcode;
  }

  public override string ToString()
  {
    var sb = new StringBuilder("DroneVideoStateResult(");
    bool __first = true;
    if (__isset.state)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("State: ");
      sb.Append(State);
    }
    if (HumanMessage != null && __isset.human_message)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("HumanMessage: ");
      sb.Append(HumanMessage);
    }
    if (RtpUrl != null && __isset.rtp_url)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("RtpUrl: ");
      sb.Append(RtpUrl);
    }
    if (Serial != null && __isset.serial)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Serial: ");
      sb.Append(Serial);
    }
    if (__isset.timestamp)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Timestamp: ");
      sb.Append(Timestamp);
    }
    sb.Append(")");
    return sb.ToString();
  }
}

