/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;



public partial class DroneRequestPosition : TBase
{
  private double _latitude;
  private double _longitude;
  private double _altitude;
  private double _heading;
  private string _serial;

  public double Latitude
  {
    get
    {
      return _latitude;
    }
    set
    {
      __isset.latitude = true;
      this._latitude = value;
    }
  }

  public double Longitude
  {
    get
    {
      return _longitude;
    }
    set
    {
      __isset.longitude = true;
      this._longitude = value;
    }
  }

  public double Altitude
  {
    get
    {
      return _altitude;
    }
    set
    {
      __isset.altitude = true;
      this._altitude = value;
    }
  }

  public double Heading
  {
    get
    {
      return _heading;
    }
    set
    {
      __isset.heading = true;
      this._heading = value;
    }
  }

  public string Serial
  {
    get
    {
      return _serial;
    }
    set
    {
      __isset.serial = true;
      this._serial = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool latitude;
    public bool longitude;
    public bool altitude;
    public bool heading;
    public bool serial;
  }

  public DroneRequestPosition()
  {
  }

  public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Double)
            {
              Latitude = await iprot.ReadDoubleAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.Double)
            {
              Longitude = await iprot.ReadDoubleAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.Double)
            {
              Altitude = await iprot.ReadDoubleAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 4:
            if (field.Type == TType.Double)
            {
              Heading = await iprot.ReadDoubleAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 5:
            if (field.Type == TType.String)
            {
              Serial = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("DroneRequestPosition");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      if (__isset.latitude)
      {
        field.Name = "latitude";
        field.Type = TType.Double;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteDoubleAsync(Latitude, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (__isset.longitude)
      {
        field.Name = "longitude";
        field.Type = TType.Double;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteDoubleAsync(Longitude, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (__isset.altitude)
      {
        field.Name = "altitude";
        field.Type = TType.Double;
        field.ID = 3;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteDoubleAsync(Altitude, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (__isset.heading)
      {
        field.Name = "heading";
        field.Type = TType.Double;
        field.ID = 4;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteDoubleAsync(Heading, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (Serial != null && __isset.serial)
      {
        field.Name = "serial";
        field.Type = TType.String;
        field.ID = 5;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteStringAsync(Serial, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    var other = that as DroneRequestPosition;
    if (other == null) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.latitude == other.__isset.latitude) && ((!__isset.latitude) || (System.Object.Equals(Latitude, other.Latitude))))
      && ((__isset.longitude == other.__isset.longitude) && ((!__isset.longitude) || (System.Object.Equals(Longitude, other.Longitude))))
      && ((__isset.altitude == other.__isset.altitude) && ((!__isset.altitude) || (System.Object.Equals(Altitude, other.Altitude))))
      && ((__isset.heading == other.__isset.heading) && ((!__isset.heading) || (System.Object.Equals(Heading, other.Heading))))
      && ((__isset.serial == other.__isset.serial) && ((!__isset.serial) || (System.Object.Equals(Serial, other.Serial))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if(__isset.latitude)
        hashcode = (hashcode * 397) + Latitude.GetHashCode();
      if(__isset.longitude)
        hashcode = (hashcode * 397) + Longitude.GetHashCode();
      if(__isset.altitude)
        hashcode = (hashcode * 397) + Altitude.GetHashCode();
      if(__isset.heading)
        hashcode = (hashcode * 397) + Heading.GetHashCode();
      if(__isset.serial)
        hashcode = (hashcode * 397) + Serial.GetHashCode();
    }
    return hashcode;
  }

  public override string ToString()
  {
    var sb = new StringBuilder("DroneRequestPosition(");
    bool __first = true;
    if (__isset.latitude)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Latitude: ");
      sb.Append(Latitude);
    }
    if (__isset.longitude)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Longitude: ");
      sb.Append(Longitude);
    }
    if (__isset.altitude)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Altitude: ");
      sb.Append(Altitude);
    }
    if (__isset.heading)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Heading: ");
      sb.Append(Heading);
    }
    if (Serial != null && __isset.serial)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Serial: ");
      sb.Append(Serial);
    }
    sb.Append(")");
    return sb.ToString();
  }
}

