/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum DroneLiveVideoState
{
  LIVE = 0,
  STOPPED = 1,
  DIED = 2,
  INVALID_CONDITION = 3,
}
