/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;



public partial class DroneSendLiveVideoRequest : TBase
{
  private string _room_secret;
  private long _room_id;

  public string RoomSecret
  {
    get
    {
      return _room_secret;
    }
    set
    {
      __isset.room_secret = true;
      this._room_secret = value;
    }
  }

  public long RoomId
  {
    get
    {
      return _room_id;
    }
    set
    {
      __isset.room_id = true;
      this._room_id = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool room_secret;
    public bool room_id;
  }

  public DroneSendLiveVideoRequest()
  {
  }

  public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String)
            {
              RoomSecret = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.I64)
            {
              RoomId = await iprot.ReadI64Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("DroneSendLiveVideoRequest");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      if (RoomSecret != null && __isset.room_secret)
      {
        field.Name = "room_secret";
        field.Type = TType.String;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteStringAsync(RoomSecret, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (__isset.room_id)
      {
        field.Name = "room_id";
        field.Type = TType.I64;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI64Async(RoomId, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    var other = that as DroneSendLiveVideoRequest;
    if (other == null) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.room_secret == other.__isset.room_secret) && ((!__isset.room_secret) || (System.Object.Equals(RoomSecret, other.RoomSecret))))
      && ((__isset.room_id == other.__isset.room_id) && ((!__isset.room_id) || (System.Object.Equals(RoomId, other.RoomId))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if(__isset.room_secret)
        hashcode = (hashcode * 397) + RoomSecret.GetHashCode();
      if(__isset.room_id)
        hashcode = (hashcode * 397) + RoomId.GetHashCode();
    }
    return hashcode;
  }

  public override string ToString()
  {
    var sb = new StringBuilder("DroneSendLiveVideoRequest(");
    bool __first = true;
    if (RoomSecret != null && __isset.room_secret)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("RoomSecret: ");
      sb.Append(RoomSecret);
    }
    if (__isset.room_id)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("RoomId: ");
      sb.Append(RoomId);
    }
    sb.Append(")");
    return sb.ToString();
  }
}

