/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum FlyingState
{
  LANDED = 0,
  TAKING_OFF = 1,
  HOVERING = 2,
  FLYING = 3,
  LANDING = 4,
  EMERGENCY = 5,
  USER_TAKEOFF = 6,
  MOTOR_RAMPING = 7,
  EMERGENCY_LANDING = 8,
}
