/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum GimbalCalibrationState
{
  CALIBRATED = 0,
  CALIBRATING = 1,
  UNCALIBRATED = 2,
  ERROR = 3,
}
