# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import drohub_pb2 as drohub__pb2


class DroneStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.doTakeoff = channel.unary_unary(
        '/Drone/doTakeoff',
        request_serializer=drohub__pb2.DroneRequest.SerializeToString,
        response_deserializer=drohub__pb2.DroneReply.FromString,
        )
    self.doLanding = channel.unary_unary(
        '/Drone/doLanding',
        request_serializer=drohub__pb2.DroneRequest.SerializeToString,
        response_deserializer=drohub__pb2.DroneReply.FromString,
        )
    self.getPosition = channel.unary_stream(
        '/Drone/getPosition',
        request_serializer=drohub__pb2.DroneRequest.SerializeToString,
        response_deserializer=drohub__pb2.DronePosition.FromString,
        )
    self.getBatteryLevel = channel.unary_stream(
        '/Drone/getBatteryLevel',
        request_serializer=drohub__pb2.DroneRequest.SerializeToString,
        response_deserializer=drohub__pb2.DroneBatteryLevel.FromString,
        )
    self.moveToPosition = channel.unary_unary(
        '/Drone/moveToPosition',
        request_serializer=drohub__pb2.DroneRequestPosition.SerializeToString,
        response_deserializer=drohub__pb2.DroneReply.FromString,
        )


class DroneServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def doTakeoff(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def doLanding(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getPosition(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getBatteryLevel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def moveToPosition(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DroneServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'doTakeoff': grpc.unary_unary_rpc_method_handler(
          servicer.doTakeoff,
          request_deserializer=drohub__pb2.DroneRequest.FromString,
          response_serializer=drohub__pb2.DroneReply.SerializeToString,
      ),
      'doLanding': grpc.unary_unary_rpc_method_handler(
          servicer.doLanding,
          request_deserializer=drohub__pb2.DroneRequest.FromString,
          response_serializer=drohub__pb2.DroneReply.SerializeToString,
      ),
      'getPosition': grpc.unary_stream_rpc_method_handler(
          servicer.getPosition,
          request_deserializer=drohub__pb2.DroneRequest.FromString,
          response_serializer=drohub__pb2.DronePosition.SerializeToString,
      ),
      'getBatteryLevel': grpc.unary_stream_rpc_method_handler(
          servicer.getBatteryLevel,
          request_deserializer=drohub__pb2.DroneRequest.FromString,
          response_serializer=drohub__pb2.DroneBatteryLevel.SerializeToString,
      ),
      'moveToPosition': grpc.unary_unary_rpc_method_handler(
          servicer.moveToPosition,
          request_deserializer=drohub__pb2.DroneRequestPosition.FromString,
          response_serializer=drohub__pb2.DroneReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Drone', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
